CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 telegram_user_id BIGINT NOT NULL UNIQUE CHECK (telegram_user_id > 0),
 username VARCHAR(80), first_name VARCHAR(100), language VARCHAR(10) NOT NULL DEFAULT 'en',
 timezone VARCHAR(80) NOT NULL DEFAULT 'UTC', onboarded BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE exercises (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT REFERENCES users(id), name VARCHAR(80) NOT NULL,
 category VARCHAR(40) NOT NULL, metric_type VARCHAR(20) NOT NULL,
 is_custom BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL,
 CHECK (metric_type IN ('STRENGTH','BODYWEIGHT','CARDIO','TIMED')),
 CHECK (is_custom = (user_id IS NOT NULL))
);
CREATE UNIQUE INDEX exercise_global_name ON exercises(lower(name)) WHERE user_id IS NULL;
CREATE UNIQUE INDEX exercise_user_name ON exercises(user_id, lower(name)) WHERE user_id IS NOT NULL;
