CREATE TABLE workout_templates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
 name VARCHAR(80) NOT NULL, description VARCHAR(500), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX template_user ON workout_templates(user_id, deleted);
CREATE TABLE workout_template_exercises (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 workout_template_id BIGINT NOT NULL REFERENCES workout_templates(id) ON DELETE CASCADE,
 exercise_id BIGINT NOT NULL REFERENCES exercises(id), position INTEGER NOT NULL CHECK(position >= 0),
 target_sets INTEGER CHECK(target_sets BETWEEN 1 AND 100), target_reps INTEGER CHECK(target_reps BETWEEN 0 AND 1000),
 target_weight NUMERIC(10,3) CHECK(target_weight BETWEEN 0 AND 2000), rest_seconds INTEGER CHECK(rest_seconds BETWEEN 0 AND 3600)
);
CREATE INDEX template_items ON workout_template_exercises(workout_template_id, position);
CREATE TABLE workout_sessions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
 workout_template_id BIGINT REFERENCES workout_templates(id), name VARCHAR(80) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('ACTIVE','COMPLETED','CANCELLED')),
 started_at TIMESTAMPTZ NOT NULL, finished_at TIMESTAMPTZ, notes VARCHAR(500),
 current_position INTEGER NOT NULL DEFAULT 0,
 request_key VARCHAR(100) NOT NULL, UNIQUE(user_id, request_key),
 CHECK ((status = 'ACTIVE' AND finished_at IS NULL) OR (status <> 'ACTIVE' AND finished_at IS NOT NULL))
);
CREATE UNIQUE INDEX one_active_session_per_user ON workout_sessions(user_id) WHERE status = 'ACTIVE';
CREATE INDEX session_history ON workout_sessions(user_id, status, started_at DESC);
CREATE TABLE workout_session_exercises (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 workout_session_id BIGINT NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE,
 exercise_id BIGINT NOT NULL REFERENCES exercises(id), name VARCHAR(80) NOT NULL,
 metric_type VARCHAR(20) NOT NULL, position INTEGER NOT NULL,
 target_sets INTEGER, target_reps INTEGER, target_weight NUMERIC(10,3), rest_seconds INTEGER,
 UNIQUE(workout_session_id, position)
);
CREATE INDEX session_exercise_history ON workout_session_exercises(exercise_id, workout_session_id);
