CREATE TABLE exercise_sets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 workout_session_exercise_id BIGINT NOT NULL REFERENCES workout_session_exercises(id) ON DELETE CASCADE,
 set_number INTEGER NOT NULL CHECK(set_number > 0), weight NUMERIC(10,3) CHECK(weight BETWEEN 0 AND 2000),
 repetitions INTEGER CHECK(repetitions BETWEEN 0 AND 1000), duration_seconds INTEGER CHECK(duration_seconds BETWEEN 1 AND 604800),
 distance NUMERIC(12,3) CHECK(distance BETWEEN 0 AND 10000), rpe NUMERIC(3,1) CHECK(rpe BETWEEN 1 AND 10),
 notes VARCHAR(500), created_at TIMESTAMPTZ NOT NULL, request_key VARCHAR(100) NOT NULL,
 voided BOOLEAN NOT NULL DEFAULT FALSE,
 UNIQUE(workout_session_exercise_id, set_number), UNIQUE(workout_session_exercise_id, request_key),
 CHECK (repetitions IS NOT NULL OR duration_seconds IS NOT NULL)
);
CREATE TABLE personal_records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id), exercise_id BIGINT NOT NULL REFERENCES exercises(id),
 max_weight NUMERIC(10,3) NOT NULL, max_reps INTEGER NOT NULL,
 best_set_volume NUMERIC(16,3) NOT NULL, best_session_volume NUMERIC(16,3) NOT NULL,
 estimated_one_rm NUMERIC(16,3) NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 UNIQUE(user_id, exercise_id)
);
CREATE TABLE bot_states (
 user_id BIGINT PRIMARY KEY REFERENCES users(id), chat_id BIGINT NOT NULL, message_id BIGINT,
 revision BIGINT NOT NULL DEFAULT 0, flow VARCHAR(40) NOT NULL DEFAULT 'HOME',
 context TEXT NOT NULL DEFAULT '{}', screen TEXT, pending BOOLEAN NOT NULL DEFAULT FALSE,
 retry_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX pending_bot_screens ON bot_states(retry_at) WHERE pending;
CREATE TABLE bot_cursor (id INTEGER PRIMARY KEY CHECK(id = 1), next_update BIGINT NOT NULL);
INSERT INTO bot_cursor VALUES (1,0);
