INSERT INTO exercises(name, category, metric_type, is_custom, created_at) VALUES
 ('Bench Press','Chest','STRENGTH',false,now()),
 ('Incline Bench Press','Chest','STRENGTH',false,now()),
 ('Dumbbell Bench Press','Chest','STRENGTH',false,now()),
 ('Push Ups','Chest','BODYWEIGHT',false,now()),
 ('Pull Ups','Back','BODYWEIGHT',false,now()),
 ('Lat Pulldown','Back','STRENGTH',false,now()),
 ('Barbell Row','Back','STRENGTH',false,now()),
 ('Seated Cable Row','Back','STRENGTH',false,now()),
 ('Squat','Legs','STRENGTH',false,now()),
 ('Leg Press','Legs','STRENGTH',false,now()),
 ('Romanian Deadlift','Legs','STRENGTH',false,now()),
 ('Leg Extension','Legs','STRENGTH',false,now()),
 ('Leg Curl','Legs','STRENGTH',false,now()),
 ('Calf Raise','Legs','STRENGTH',false,now()),
 ('Overhead Press','Shoulders','STRENGTH',false,now()),
 ('Shoulder Press','Shoulders','STRENGTH',false,now()),
 ('Dumbbell Shoulder Press','Shoulders','STRENGTH',false,now()),
 ('Lateral Raise','Shoulders','STRENGTH',false,now()),
 ('Barbell Curl','Arms','STRENGTH',false,now()),
 ('Dumbbell Curl','Arms','STRENGTH',false,now()),
 ('Triceps Pushdown','Arms','STRENGTH',false,now()),
 ('Dips','Arms','BODYWEIGHT',false,now()),
 ('Plank','Core','TIMED',false,now()),
 ('Crunch','Core','BODYWEIGHT',false,now()),
 ('Running','Cardio','CARDIO',false,now()),
 ('Cycling','Cardio','CARDIO',false,now()),
 ('Rowing','Cardio','CARDIO',false,now());
