ALTER TABLE workout_template_exercises ADD COLUMN target_duration INTEGER CHECK(target_duration BETWEEN 1 AND 604800), ADD COLUMN target_distance NUMERIC(12,3) CHECK(target_distance BETWEEN 0 AND 10000), ADD COLUMN set_plan TEXT NOT NULL DEFAULT '[]';
ALTER TABLE workout_session_exercises ADD COLUMN target_duration INTEGER CHECK(target_duration BETWEEN 1 AND 604800), ADD COLUMN target_distance NUMERIC(12,3) CHECK(target_distance BETWEEN 0 AND 10000), ADD COLUMN set_plan TEXT NOT NULL DEFAULT '[]', ADD COLUMN skipped BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE workout_session_exercises DROP CONSTRAINT workout_session_exercises_workout_session_id_position_key;
ALTER TABLE workout_session_exercises ADD CONSTRAINT session_exercise_position UNIQUE(workout_session_id,position) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE exercise_sets ADD COLUMN warmup BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE workout_sessions ADD COLUMN paused_at TIMESTAMPTZ, ADD COLUMN paused_seconds BIGINT NOT NULL DEFAULT 0 CHECK(paused_seconds >= 0), ADD COLUMN rest_until TIMESTAMPTZ;
CREATE TABLE training_preferences (
 user_id BIGINT PRIMARY KEY REFERENCES users(id), weekly_goal INTEGER NOT NULL DEFAULT 3 CHECK(weekly_goal BETWEEN 1 AND 14),
 rest_notifications BOOLEAN NOT NULL DEFAULT FALSE, weight_step NUMERIC(8,3) NOT NULL DEFAULT 2.5 CHECK(weight_step BETWEEN 0.125 AND 100),
 rep_min INTEGER NOT NULL DEFAULT 8 CHECK(rep_min BETWEEN 1 AND 100), rep_max INTEGER NOT NULL DEFAULT 12 CHECK(rep_max BETWEEN 1 AND 100), CHECK(rep_max >= rep_min)
);
CREATE TABLE training_schedule (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id), template_id BIGINT NOT NULL REFERENCES workout_templates(id),
 local_start TIMESTAMP NOT NULL, repeat_weeks INTEGER NOT NULL DEFAULT 0 CHECK(repeat_weeks BETWEEN 0 AND 4), reminders BOOLEAN NOT NULL DEFAULT FALSE,
 notified_at TIMESTAMPTZ, cancelled BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX training_schedule_user ON training_schedule(user_id,local_start) WHERE NOT cancelled;
CREATE TABLE template_imports (user_id BIGINT NOT NULL REFERENCES users(id), fingerprint VARCHAR(64) NOT NULL, template_id BIGINT NOT NULL REFERENCES workout_templates(id), PRIMARY KEY(user_id,fingerprint));
CREATE TABLE history_imports (user_id BIGINT NOT NULL REFERENCES users(id), fingerprint VARCHAR(64) NOT NULL, PRIMARY KEY(user_id,fingerprint));
CREATE TABLE exercise_aliases (alias VARCHAR(80) PRIMARY KEY, exercise_id BIGINT NOT NULL REFERENCES exercises(id));
INSERT INTO exercise_aliases SELECT 'жим лёжа',id FROM exercises WHERE user_id IS NULL AND name='Bench Press';
INSERT INTO exercise_aliases SELECT 'жим лежа',id FROM exercises WHERE user_id IS NULL AND name='Bench Press';
INSERT INTO exercise_aliases SELECT 'жим над головой',id FROM exercises WHERE user_id IS NULL AND name='Shoulder Press';
INSERT INTO exercise_aliases SELECT 'приседания',id FROM exercises WHERE user_id IS NULL AND name='Squat';
INSERT INTO exercise_aliases SELECT 'бег',id FROM exercises WHERE user_id IS NULL AND name='Running';
INSERT INTO exercise_aliases SELECT 'отжимания',id FROM exercises WHERE user_id IS NULL AND name='Push Ups';
